jsonrpc:
    discovery:
        zookeeper: localhost:2181
    client:
        serverList: localhost:12306
        connectionTimeoutMS: 5000
        invokeTimeoutMS: 1000
spring:
    resources:
        chain:
            cache: false